/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import app.rheno.Util;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
       	System.out.println(new App().getGreeting());
	
	Util u = new Util();
	System.out.println(u.powerOfTwo(11));
    }
}
